// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5001/' | (string & {});
};

export type AuthTokensResponse = {
    accessToken: string;
    refreshToken: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type RevokeRequest = {
    refreshToken: string;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostAuthRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type PostAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthTokensResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostAuthRefreshError = PostAuthRefreshErrors[keyof PostAuthRefreshErrors];

export type PostAuthRefreshResponses = {
    /**
     * OK
     */
    200: AuthTokensResponse;
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthRevokeData = {
    body: RevokeRequest;
    path?: never;
    query?: never;
    url: '/auth/revoke';
};

export type PostAuthRevokeErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostAuthRevokeError = PostAuthRevokeErrors[keyof PostAuthRevokeErrors];

export type PostAuthRevokeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostAuthRevokeResponse = PostAuthRevokeResponses[keyof PostAuthRevokeResponses];
